### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by kristianmandrup** [paulvanbladel/aureliauth#7]
I recommend that you follow the Aurelia "naming standard" and rename it `aurelia-auth` or perhaps even better, `aurelia-token-auth` since there might well be other auth plugins (such as JWT etc.) down the line...

**Comment by paulvanbladel** [comment]
Hi Kristian,
Thanks for the suggestion. The reason I took a more 'frivolous' name because I thought the aurelia-abc naming was kind of reserved for the 'official' aurelia plugins.
Maybe someone from the aurelia core team should advice here.

**Comment by PWKad** [comment]
Generally when 'naming' the plugins I recommend that the repository contains the word aurelia because it helps others find it.  Dasherizing it is helpful as well of course.

When this is actually loaded via JSPM or wherever else it will be clear that this is not an official repo because those always originate from the `github:aurelia/{whatever}` namespace on github.  The community contributions will come across like this - `github:paulvanbladel/aurelia-token-auth` or w/e so it's pretty clear for us (IMO)

If you plan on expanding the features to include other types of authentication then `aurelia-auth` makes sense, elsewise I can see the case for naming it `aurelia-token-auth` 

Thanks again for the contributions to the community!

**Comment by kristianmandrup** [comment]
Awesome :) Good points!! I think for now it should be named `aurelia-token-auth` to make it clear that it is (for now at least) token based authentication only.

**Comment by paulvanbladel** [comment]
Let's try to be future proof and name it aurelia-auth.
